'''
    This program analyzes log files generated by other Python programs by
    searching for key phrases that indicate success or failure.

    Name:       Log Analyzer
    Creator:    Matt Gagnon <mattjgagnon@gmail.com>
    Created:    2012-08-15
    Revised:
    Version:    1.0 (initial release)
    Python:     2.6
    Dependency: None
    To Do:      Abstract a config file per Python program log
                Access actual server for real time log file data
                Better reporting, maybe a csv file updated daily
'''

# =============
# CONFIGURATION
# =============
## XO
##phrase_list = [
##    'INFO - --->data submitted',
##    'INFO - the form submitted successfully',
##    'ERROR - There was an error on the server'
##    ]
##filename = '\\\\vindicate2\\files\\mgagnon\\xo-leadmaster-transfer\\logs\\2012-05-xo-leadmaster-transfer.log'
##filename = '\\\\vindicate2\\files\\mgagnon\\xo-leadmaster-transfer\\logs\\2012-06-xo-leadmaster-transfer.log'
##filename = '\\\\vindicate2\\files\\mgagnon\\xo-leadmaster-transfer\\logs\\2012-07-xo-leadmaster-transfer.log'
##filename = '\\\\vindicate2\\files\\mgagnon\\xo-leadmaster-transfer\\logs\\2012-08-xo-leadmaster-transfer.log'
## HP
##phrase_list = [
##    'INFO - database sql',
##    'INFO - insert record status: success',
##    'ERROR - insert record status: failure'
##    ]
##filename = '\\\\vindicate2\\files\\mgagnon\\hp-email-importer\\logs\\2012-06-hp-email-importer.log'
##filename = '\\\\vindicate2\\files\\mgagnon\\hp-email-importer\\logs\\2012-07-hp-email-importer.log'
##filename = '\\\\vindicate2\\files\\mgagnon\\hp-email-importer\\logs\\2012-08-hp-email-importer.log'
## WMS
phrase_list = [
    # older version
    'WMS email successfully handled',
    'Attempting to process the following email',
    # newer version
    'Database error',
    'insertCompany',
    'InsertCompany success',
    'InsertCompany failure',
    'InsertContact',
    'InsertContact success',
    'InsertContact failure',
    'UpdateContact',
    'UpdateContact success',
    'UpdateContact failure',
    'InsertSOWRecord',
    'InsertSOWRecord success',
    'InsertSOWRecord failure'
    ]
filename = '\\\\vindicate2\\files\\mgagnon\\wmsemailprocessor\\wmslogs\\wmslog_2012-01-07.txt'

# =========
# FUNCTIONS
# =========
def filefind(word, filename):
    import sys

    # initialize count
    linecount = 0
    wordcount = 0

    # can we open file? if so, return file handle
    try:
        fh = open(filename, 'r')
    # if not, exit
    except:
        print filename, ":", sys.exc_value[1]
        sys.exit(1)

    # Open file, read and process each line, close file
    fh = open(filename, 'r')

    for eachLine in fh:
        # count number of occurrences of word in line
        hits = eachLine.count(word)

        if hits > 0:
            linecount = linecount + 1
            wordcount = wordcount + hits
##            print eachLine,    # development

    fh.close()

    # return the word count
    return wordcount

# =========
# MAIN CODE
# =========
results = {}

for phrase in phrase_list:
    results[phrase] = filefind(phrase, filename)

print results
